name: date_util
description: A complete date utility library in dart language.
version: 0.0.1
homepage: https://github.com/corpsgeek/Date-Utility/tree/master/dateUtil
author: Adetu Ridwan, Egbesola Anthony <bethetechnology@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^0.12.0
